apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  # LoadBalancer публикует Grafana через minikube tunnel.
  type: LoadBalancer
  # Значения адреса и порта берутся из values.yaml.
  externalIPs:
    - {{ .Values.EXTERNAL_IP }}

  ports:
    - name: "{{ .Values.EXTERNAL_PORT }}"
      port: {{ .Values.EXTERNAL_PORT }}
      targetPort: 3000
  selector:
    io.kompose.service: grafana
