apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# Все имена ресурсов получат префикс dev-.
namePrefix: dev-

# Добавляем env=dev и в labels, и в selectors. Это изолирует dev от prod.
labels:
  - includeSelectors: true
    pairs:
      env: dev

# Первый патч задаёт dev-параметры Deployment, второй меняет порт Service.
patches:
  - path: flask-deployment-patch.yaml
  - target:
      version: v1
      kind: Service
      name: service-devops
    path: flask-service-port-patch.yaml
