apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flask-service.yml
  - flask.yml
  - redis-service.yml
  - redis.yml

# Добавляем общий label ко всем yaml объектам перечисленным выше.
labels:
  # добавляем не только в metadata, но и в selectors
  - includeSelectors: true
    pairs:
      app: devops-course-2026
