apiVersion: v1
# Service с именем redis нужен, чтобы Flask мог подключаться к Redis по DNS-имени redis.
kind: Service

metadata:
  name: redis
  labels:
    app: flask-app

spec:
  # ClusterIP доступен только внутри кластера, наружу Redis открывать не нужно.
  type: ClusterIP

  # Направляем трафик только в Pod Redis.
  selector:
    app: flask-app
    svc: db

  ports:
    - name: redis
      protocol: TCP
      # Порт Service, на который ходит Flask.
      port: 6379
      # Порт контейнера Redis.
      targetPort: 6379
